on: push
jobs:
  build:
    runs-on: [linux,macOS]
    name: build
    steps:
    - uses: actions/checkout@v4
    - uses: bazelbuild/setup-bazelisk@v3
    - name: Mount bazel cache  # Optional
      uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: bazel
    - run: bazel build //...
